server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/authdb
    username: root
    password: Francesco90
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  application:
    name: auth-service

jwt:
  secret: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiRnJhbmNlc2NvIn0.eaVrVjXGrFlA2TVajmKZyRBM6nHkXt02eqTHfKe7ddo
  expiration: 86400000
  refreshExpiration: 86400000   # 24 ore

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      register-with-eureka: true
      fetch-registry: true

roles:
  admin: ROLE_ADMIN
  nutritionist: ROLE_NUTRITIONIST
admin:
  email: admin@nutrihouse.it
  password: admin123
  fullName: Admin Nutrihouse
